---
language: ruby
os: linux
dist: xenial

stages:
- check
- test
- publish

# Default test job matrix.
env:
- RAILS_VERSION=5.2.6
- RAILS_VERSION=6.0.4
- RAILS_VERSION=6.1.4
- RAILS_VERSION=7.0.2
rvm:
- 2.6.9
- 2.7.5
- 3.0.3
install:
- bundle install
script:
- BACKTRACE=1 bundle exec rake test

jobs:
  exclude:
  - rvm: 3.0.3
    env: "RAILS_VERSION=5.2.6"
  - rvm: 2.6.9
    env: "RAILS_VERSION=7.0.2"
  include:
  - stage: check
    rvm: 3.0.3
    install:
    - bundle install
    script:
    - rubocop
  - stage: publish
    if: tag IS present
    rvm: 3.0.3
    install:
    - bundle install
    script:
    - "filename=`gem build rest_framework.gemspec 2>&1 | sed -e 's/.*File: \\(.*\\)/\\1/p;d'`"
    - gem push $filename
