---
language: ruby
env:
- "RAILS_VERSION=5.2.0"
- "RAILS_VERSION=6.0.0"
- "RAILS_VERSION=6.1.0"
install:
- gem install -N bundler:1.17.3
- bundle _1.17.3_ install
rvm:
- 2.5.0
- 2.6.5
- 2.7.2
- 3.0.0
jobs:
  exclude:
  - rvm: 3.0.0
    env: "RAILS_VERSION=5.2.0"
  allow_failures:
  - rvm: 3.0.0
script:
- BACKTRACE=1 bundle exec rake test
