---
language: ruby
env:
- "RAILS_VERSION=4.2"
- "RAILS_VERSION=5.2"
- "RAILS_VERSION=6.0"
before_install:
- gem uninstall bundler --force -x -a
- gem install -N bundler:1.17.3
rvm:
- 2.5.0
- 2.6.5
script:
- rake test
